<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="5" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-04-03T12:58:20 IST" name="TestNG Foundation" finished-at="2022-04-03T12:58:20 IST" duration-ms="91">
    <groups>
    </groups>
    <test started-at="2022-04-03T12:58:20 IST" name="TestNG Foundation 1" finished-at="2022-04-03T12:58:20 IST" duration-ms="22">
      <class name="TestNG2">
        <test-method signature="TestCase4()[pri:0, instance:TestNG2@4bb4de6a]" started-at="2022-04-03T12:58:20 IST" name="TestCase4" finished-at="2022-04-03T12:58:20 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase4 -->
      </class> <!-- TestNG2 -->
      <class name="TestNG1">
        <test-method signature="TestCase1()[pri:0, instance:TestNG1@16022d9d]" started-at="2022-04-03T12:58:20 IST" name="TestCase1" finished-at="2022-04-03T12:58:20 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase1 -->
        <test-method signature="TestCase2()[pri:0, instance:TestNG1@16022d9d]" started-at="2022-04-03T12:58:20 IST" name="TestCase2" finished-at="2022-04-03T12:58:20 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertFalse(Assert.java:78)
at org.testng.Assert.assertFalse(Assert.java:88)
at TestNG1.TestCase2(TestNG1.java:12)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase2 -->
      </class> <!-- TestNG1 -->
    </test> <!-- TestNG Foundation 1 -->
    <test started-at="2022-04-03T12:58:20 IST" name="TestNG Foundation 2" finished-at="2022-04-03T12:58:20 IST" duration-ms="1">
      <class name="TestNG3">
        <test-method signature="TestCase5()[pri:0, instance:TestNG3@17776a8]" started-at="2022-04-03T12:58:20 IST" name="TestCase5" finished-at="2022-04-03T12:58:20 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase5 -->
      </class> <!-- TestNG3 -->
    </test> <!-- TestNG Foundation 2 -->
  </suite> <!-- TestNG Foundation -->
</testng-results>
